name: Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/slurminade
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@master
        with:
          lfs: false
      - uses: actions/setup-python@v4
      - name: Build SDist and wheel
        run: pipx run build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
